backend:
  name: github
  repo: wuwu/mariesharp
  branch: development
  # publish_mode: editorial_workflow
  # display_url: http://localhost:4500

media_folder: "static/uploads"

collections: # A list of collections the CMS should be able to edit
  - label: "Blog"
    name: "blog"
    folder: "_posts/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Produkte"
    name: "products"
    folder: "_products/product"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Kategorie", name: "select", widget: "select", options: ["Die Klassischen", "Die Extra Schrafen", "Die Fruchtigen", "Special Editions", "other"]}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Piquancy Factor", name: "piquancy", widget: "number"}
      - {label: "Zutaten", name: "ingredients", widget: "markdown"}
      - {label: "Preis - klein", name: "priceSmall", widget: "number"}
      - {label: "Preis - groß", name: "priceLarge", widget: "number", required: false}
      - {label: "Image - Mähwerttabelle", name: "nutrition", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - label: Pages
    name: pages
    create: false
    delete: false
    files:

      - label: Impressum
        name: datenschutz
        delete: false
        file: content/pages/datenschutz.yml
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text, name: text, widget: markdown, required: false}
        meta:
          - {label: SEO Description, name: description, widget: text}

      - label: Kontakt
        name: contact
        delete: false
        file: content/pages/contact.yml
        fields:
          - {label: Image, name: image, widget: image, required: false, tagname:"" }
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Text, name: text, widget: markdown, required: false}
        meta:
          - {label: SEO Description, name: description, widget: text}

      - label: Extra Treatments
        name: extratreatments
        delete: false
        file: content/pages/extra.yml
        fields:
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Title, name: title, widget: string}
          - label: Treatment
            name: treatment
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: markdown}
        meta:
          - {label: SEO Description, name: description, widget: text}

      - label: Wellness Massagen
        name: wellness
        delete: false
        file: content/pages/wellness.yml
        fields:
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Title, name: title, widget: string}
          - label: Treatment
            name: treatment
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: markdown}
        meta:
          - {label: SEO Description, name: description, widget: text}

      - label: Gesichtsbehandlungen
        name: facial
        delete: false
        file: content/pages/facial.yml
        fields:
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - label: Treatment
            name: treatment
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: markdown}
        meta:
          - {label: SEO Description, name: description, widget: text}

      - label: Hautdiagnose
        name: hautdiagnose
        delete: false
        file: content/pages/skin.yml
        fields:
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Title, name: title, widget: string}
          - {label: Sektion Intro, name: intro, widget: text, required: false}
          - {label: Text, name: text, widget: markdown, required: false}
        meta:
          - {label: SEO Description, name: description, widget: text}

      - label: About
        name: about
        delete: false
        file: content/pages/about.yml
        fields:
          - {label: Image, name: image, widget: image, required: false, tagname: ""}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Text, name: text, widget: markdown, required: false}
        meta:
          - {label: SEO Description, name: description, widget: text}